apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: ecommerce-staging
  labels:
    app: service-discovery
    tier: infrastructure
spec:
  type: ClusterIP
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: http
  selector:
    app: service-discovery
